yellowstone: Fix compilation error with mdss_mdp_trace.h
  * When compiling with O3 optimization and a newer 4.9 toolchain
      compiler would complain with:

"include/trace/define_trace.h:79:43: fatal error: ./ozeventtrace.h: No such file or directory
  #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)"

  * According to define_trace.h we should define TRACE_INCLUDE_PATH
     for anything outside of include/trace/

Change-Id: Ieceda930cbb16c1aadf307767fe119ac9ac6d054
Signed-off-by: Josue Rivera <prbassplayer@gmail.com>
(cherry picked from commit f9e69611b7f0dd507986f914863950659e58aebb)